import type { Agency, Contact, ParentPathwaysState, TrainingOption } from "./types";
import { DEFAULT_CHECKLIST_ITEMS, defaultSourceTracking } from "./types";

/** Public-source verification date (May 2026). Re-check providers before acting. */
const VERIFIED = "2026-05-26";

type AgencyInput = {
  id: string;
  name: string;
  type: Agency["type"];
  tags: string[];
  joshRelevance: string[];
  kristyRelevance: string[];
  helpsWith: string[];
  nextAction: string;
  notes: string;
  location?: string;
  phone?: string;
  email?: string;
  website?: string;
  openingHours?: string;
  eligibilityRules?: string;
  costs?: string;
  fundingOptions?: string[];
  confidence?: Agency["confidence"];
  sourceUrl?: string;
  sourceName?: string;
  sourceNotes?: string;
};

const agency = (input: AgencyInput): Agency => ({
  ...defaultSourceTracking(),
  archived: false,
  kristyAgedCareOverride: false,
  verificationStatus: input.confidence === "high" ? "verified" : "needs_check",
  lastChecked: VERIFIED,
  verifiedBy: input.website ? "Public web research" : "",
  sourceUrl: input.website ?? "",
  sourceName: input.website ? "Official website / directory" : "Needs source",
  sourceNotes: input.website ? "Contact details from provider website or council directory (May 2026)." : "Add source URL when verified.",
  id: input.id,
  name: input.name,
  type: input.type,
  location: input.location ?? (input.tags.includes("online") ? "Online / Dubbo-relevant" : "Dubbo NSW / Central West NSW"),
  phone: input.phone ?? "",
  email: input.email ?? "",
  website: input.website ?? "",
  openingHours: input.openingHours ?? "Contact provider to confirm current hours.",
  helpsWith: input.helpsWith,
  joshRelevance: input.joshRelevance,
  kristyRelevance: input.kristyRelevance,
  eligibilityRules: input.eligibilityRules ?? "Confirm eligibility and program rules directly with the provider.",
  costs: input.costs ?? "Confirm any candidate or service fees before committing.",
  fundingOptions:
    input.fundingOptions ??
    (input.tags.includes("funding")
      ? ["Parent Pathways", "Smart and Skilled", "Fee-Free TAFE", "Workforce Australia supports"]
      : []),
  servicesOffered: input.helpsWith,
  lastVerified: VERIFIED,
  confidence: input.confidence ?? "high",
  notes: input.notes,
  nextAction: input.nextAction,
  tags: input.tags,
});

export const agenciesSeed: Agency[] = [
  agency({
    id: "spinifex",
    name: "Spinifex Recruiting",
    type: "recruiter",
    tags: ["local", "part-time", "admin", "government", "customer service", "day shift"],
    location: "46 Wingewarra Street, Dubbo NSW 2830",
    phone: "02 6884 1298",
    email: "",
    website: "https://www.spinifexrecruiting.com.au/branches/dubbo",
    openingHours: "Call office for current hours; national line 1300 800 301",
    joshRelevance: ["Thursday/Friday work", "MSP/help desk", "admin", "customer service", "government", "ICT-adjacent support"],
    kristyRelevance: ["may know local employers"],
    helpsWith: ["local recruitment", "temporary placements", "resume discussion", "local employer introductions"],
    nextAction: "Call 02 6884 1298 and ask about Thursday/Friday ICT, admin, school support, or customer service work.",
    notes: "Dubbo office covers commercial, community, renewable energy, and government lines. Use website contact form if no direct email published.",
    costs: "Recruitment is typically employer-paid; confirm any candidate fees before registering.",
  }),
  agency({
    id: "programmed",
    name: "Programmed Skilled Workforce",
    type: "recruiter",
    tags: ["labour hire", "admin", "customer service", "verify fit"],
    location: "37 Cobbora Road, Dubbo NSW 2830",
    phone: "02 6394 9500",
    website: "https://skilled.programmed.com.au/contact/",
    openingHours: "Mon–Fri business hours (confirm with office)",
    joshRelevance: ["possible admin or customer service", "possible day shift"],
    kristyRelevance: ["limited unless healthcare roles are available"],
    helpsWith: ["labour hire", "admin placements", "customer service placements"],
    nextAction: "Call 02 6394 9500 and ask specifically for day-shift Thursday/Friday admin, ICT support, or customer service roles.",
    notes: "Screen out heavy labour, night shift, and full availability requirements. National line also listed as 1300 361 582 on some directories.",
    costs: "Usually employer-funded labour hire; confirm role type before committing.",
  }),
  agency({
    id: "haynes",
    name: "Haynes People",
    type: "recruiter",
    tags: ["labour hire", "local", "verify fit"],
    location: "Level 1, 31-37 Macquarie Street, Dubbo NSW 2830",
    phone: "1300 867 106",
    email: "dubbo@haynespeople.com.au",
    website: "https://www.haynespeople.com.au/locations/",
    openingHours: "By appointment; call 1300 867 106 to book",
    joshRelevance: ["possible local placements if day-shift and structured"],
    kristyRelevance: ["limited unless healthcare roles are available"],
    helpsWith: ["recruitment", "temporary placements", "labour hire"],
    nextAction: "Call 1300 867 106 and verify non-heavy day-shift roles that fit Thursday/Friday only.",
    notes: "Strong in renewables, civil, warehousing, and mining — confirm role is not heavy labour before proceeding.",
  }),
  agency({
    id: "joblink-plus",
    name: "Joblink Plus",
    type: "employment service",
    tags: ["training", "resume support", "employment service", "local", "funding"],
    location: "2/62 Wingewarra Street, Dubbo NSW 2830 (also listed at 138 Talbragar Street)",
    phone: "02 6841 6300",
    email: "",
    website: "https://www.joblinkplus.com.au/locations/dubbo",
    openingHours: "Mon–Fri 8:30am–5:00pm",
    eligibilityRules: "Services depend on your Centrelink/Workforce Australia stream — bring ID and current payment details.",
    joshRelevance: ["resume support", "training support", "local employment planning"],
    kristyRelevance: ["return-to-work planning", "confidence rebuilding", "family-friendly work planning"],
    helpsWith: ["employment coaching", "training referrals", "resume help", "interview prep"],
    nextAction: "Call 1800 695 625 or Dubbo 02 6841 6300 and ask what practical support is available this week.",
    notes: "National enquiries 1800 695 625. Confirm which Dubbo address is current for your service type.",
    costs: "Core employment services are usually free for eligible participants; paid courses may still apply.",
  }),
  agency({
    id: "sureway",
    name: "Sureway Employment and Training",
    type: "employment service",
    tags: ["training", "employment service", "resume support", "funding"],
    location: "Shop 1, 24 Talbragar Street, Dubbo NSW 2830",
    phone: "1300 787 392",
    website: "https://www.sureway.com.au/about-sureway/our-locations/dubbo/",
    openingHours: "Mon–Fri 9:00am–5:00pm",
    eligibilityRules: "Inclusive Employment Australia and Workforce Australia streams — eligibility confirmed at intake.",
    joshRelevance: ["training support", "local employer connections"],
    kristyRelevance: ["return-to-work planning", "possible family-friendly planning"],
    helpsWith: ["job search support", "training referrals", "resume help"],
    nextAction: "Call 1300 787 392 and ask about funded training and specific local employer links.",
    notes: "Also services Wellington region. Head office Wagga Wagga for escalations.",
    costs: "Many participant services are subsidised; confirm training co-contributions upfront.",
  }),
  agency({
    id: "apm",
    name: "APM Employment Services",
    type: "employment service",
    tags: ["employment service", "DES", "verify fit", "funding"],
    location: "Shop 2, 88-90 Macquarie Street, Dubbo NSW 2830",
    phone: "02 6884 3290",
    email: "support@apm.net.au",
    website: "https://apm.net.au/find-us/dubbo",
    openingHours: "Mon–Fri 9:00am–5:00pm",
    eligibilityRules: "Inclusive Employment Australia (formerly DES) and related streams — confirm your referral status.",
    joshRelevance: ["structured employment support", "possible training support"],
    kristyRelevance: ["return-to-work planning"],
    helpsWith: ["employment coaching", "job search support", "provider referrals"],
    nextAction: "Call 02 6884 3290 or national 1800 276 276 and ask what concrete support they can offer this week.",
    notes: "Use only if the stream and benefit are clear for your situation.",
    costs: "Participant services typically no direct fee; verify funding for courses, transport, or tools.",
  }),
  agency({
    id: "yilabara",
    name: "Yilabara Dubbo / Parent Pathways",
    type: "Parent Pathways",
    tags: ["parent pathways", "funding", "confidence", "family-friendly", "training", "local"],
    location: "Suite 2, First Floor, 64 Talbragar Street, Dubbo NSW 2830",
    phone: "02 5858 4597",
    email: "parents-dubbo@yilabara.org.au",
    website: "https://yilabara.org.au/programs/parentpathways/",
    openingHours: "Call to confirm appointment times",
    eligibilityRules:
      "Parent Pathways supports eligible parents/carers of children under 6 in Western NSW. Confirm Kristy's eligibility even if not on Parenting Payment.",
    costs: "Program may fund training, checks, transport, and work-related costs for eligible participants — confirm individual fund rules.",
    fundingOptions: ["Parent Pathways individual support fund", "training subsidies", "work-related expense support"],
    joshRelevance: ["ask whether any support extends to Josh"],
    kristyRelevance: ["return-to-work confidence", "paediatric RN relocating to Dubbo", "training funding", "family-friendly nursing pathway planning"],
    helpsWith: ["Parent Pathways", "appointments", "action plans", "training support", "funding discussions"],
    nextAction: "Email parents-dubbo@yilabara.org.au or call 02 5858 4597 to book and run through the funding checklist.",
    notes: "LinkedIn also lists 02 7255 0728 — use official program contacts first.",
  }),
  agency({
    id: "nsw-health",
    name: "NSW Health / I Work for NSW",
    type: "government",
    tags: ["nursing", "hospital", "community health", "outpatient", "government", "not aged care", "local"],
    location: "Western NSW LHD — search Dubbo and regional listings online",
    phone: "1800 829 633",
    email: "",
    website: "https://www.health.nsw.gov.au/careers",
    openingHours: "Online applications 24/7; recruitment enquiries business hours",
    eligibilityRules: "AHPRA registration required for clinical roles; admin/ICT roles have separate criteria.",
    costs: "No agency fee; relocation or checks may apply per role.",
    joshRelevance: ["possible ICT/admin support roles via I Work for NSW"],
    kristyRelevance: ["hospital casual pool", "community health", "outpatient nursing", "family-friendly shifts to confirm"],
    helpsWith: ["job vacancies", "clinical roles", "admin and ICT roles"],
    nextAction: "Search health.nsw.gov.au careers for casual pool, outpatient, clinic, community, school, and child/family roles — exclude aged care listings.",
    notes: "Also search I Work for NSW for broader government ICT/admin roles in Dubbo region.",
  }),
  agency({
    id: "dubbo-council",
    name: "Dubbo Regional Council",
    type: "employer",
    tags: ["government", "admin", "library", "customer service", "day shift", "local"],
    location: "Dubbo NSW — see current vacancies for site",
    phone: "02 6801 3400",
    email: "info@dubbo.nsw.gov.au",
    website: "https://www.dubbo.nsw.gov.au/Careers",
    openingHours: "Council customer service Mon–Fri (see website)",
    eligibilityRules: "Each vacancy lists citizenship, WWCC, and qualification requirements.",
    costs: "No recruitment fee; standard government checks may apply.",
    joshRelevance: ["library/admin", "customer service", "systems support", "predictable day work"],
    kristyRelevance: ["limited nursing relevance"],
    helpsWith: ["local government roles", "admin", "customer service", "library", "systems support"],
    nextAction: "Check dubbo.nsw.gov.au careers weekly and save roles with Thursday/Friday or part-time fit.",
    notes: "Good source for predictable local government day work.",
  }),
  agency({
    id: "tafe-nsw",
    name: "TAFE NSW Dubbo",
    type: "training provider",
    tags: ["training", "TAFE", "TAE40122", "ICT", "business", "funding", "online"],
    location: "Myall Street & Narromine Road campuses, Dubbo NSW 2830",
    phone: "131 601",
    email: "Support@tafensw.edu.au",
    website: "https://www.tafensw.edu.au/locations/dubbo-myall-street",
    openingHours: "Campus customer service Mon–Fri 8:30am–4:30pm; phone support Mon–Fri 8am–6pm",
    eligibilityRules: "Smart and Skilled subsidies and Fee-Free TAFE depend on prior qualifications and course — ask at enrolment.",
    costs: "Course fees vary; Fee-Free TAFE and subsidies may reduce cost — get a quote before enrolling.",
    fundingOptions: ["Smart and Skilled", "Fee-Free TAFE", "Parent Pathways (if eligible)", "employer sponsorship"],
    joshRelevance: ["TAE40122", "ICT certificates", "business/admin", "digital trainer pathway"],
    kristyRelevance: ["possible CPD/refresher pathways"],
    helpsWith: ["TAFE courses", "TAE40122", "ICT certificates", "business/admin", "Fee-Free TAFE checks"],
    nextAction: "Call 131 601 and ask about TAE40122 delivery days, workload, subsidies, and online/blended options around Monday/Wednesday work.",
    notes: "TAFE Digital available for many online units. Disability support: DisabilityAndAccessStudentSupport@tafensw.edu.au",
  }),
  agency({
    id: "nursing-agencies",
    name: "Nursing agencies (Dubbo region)",
    type: "nursing agency",
    tags: ["nursing", "part-time", "casual", "aged care risk", "verify fit"],
    location: "Dubbo NSW — multiple agencies",
    phone: "02 6884 3290",
    website: "https://www.health.nsw.gov.au/careers",
    openingHours: "Varies by agency",
    eligibilityRules: "AHPRA registration and current clinical checks required.",
    costs: "Agency placement usually no fee to nurse; confirm pay rates and penalties.",
    joshRelevance: [],
    kristyRelevance: ["nursing work", "part-time/casual", "screen for non-aged-care roles"],
    helpsWith: ["nursing placement", "shift matching", "hospital casual pool"],
    nextAction:
      "Contact NSW Health casual pool and nursing agencies; ask explicitly to exclude aged care/RACF and prefer clinic, GP, community, or hospital pool.",
    notes:
      "Consider Western NSW LHD casual pool, local GP clinics, and agencies found via health careers. Always confirm shift type before accepting.",
    confidence: "medium",
  }),
];

const course = (
  id: string,
  person: TrainingOption["person"],
  courseName: string,
  provider: string,
  priority: TrainingOption["priority"],
  deliveryMode: TrainingOption["deliveryMode"],
  scores: Partial<TrainingOption>,
  jobsUnlocked: string[],
  questions: string[],
  notes: string,
  extras?: Partial<Pick<TrainingOption, "cost" | "fundingPossible" | "duration">>,
): TrainingOption => ({
  ...defaultSourceTracking(),
  archived: false,
  verificationStatus: "needs_check",
  lastChecked: VERIFIED,
  verifiedBy: "",
  sourceName: "Course provider — verify",
  sourceNotes: "Confirm current intake, cost, and subsidies before enrolling.",
  id,
  person,
  course: courseName,
  provider,
  cost: extras?.cost ?? "Confirm current fee with provider",
  fundingPossible:
    extras?.fundingPossible ??
    "Ask Parent Pathways, Smart and Skilled, Fee-Free TAFE, Workforce Australia, or employer support where relevant",
  deliveryMode,
  duration: extras?.duration ?? "Confirm current intake dates and weekly workload",
  priority,
  status: "Idea",
  employabilityImpact: 6,
  timeFit: 6,
  costFit: 6,
  fundingAvailability: 5,
  strengthsAlignment: 7,
  availabilityFit: 7,
  stressFit: 7,
  longTermValue: 7,
  jobsUnlocked,
  questions,
  notes,
  lastVerified: VERIFIED,
  ...scores,
});

export const trainingSeed: TrainingOption[] = [
  course(
    "ms-365",
    "josh",
    "Microsoft 365 Fundamentals (MS-900)",
    "Microsoft Learn + Certiport exam centre",
    "Contact this week",
    "online",
    { employabilityImpact: 8, timeFit: 9, strengthsAlignment: 10, availabilityFit: 9, longTermValue: 8, costFit: 9 },
    ["Microsoft 365 support", "MSP Level 1-2", "school ICT", "admin systems support"],
    ["Can exam fees be funded?", "Which path supports M365 admin work fastest?"],
    "Direct match for Avance MSP role — M365, ticketing, and device support already in daily use.",
    { cost: "Learning free on Microsoft Learn; exam ~AUD $165 (confirm current Certiport price)", duration: "Self-paced; exam when ready" },
  ),
  course(
    "tae40122",
    "josh",
    "TAE40122 Certificate IV in Training and Assessment",
    "TAFE NSW Dubbo / TAFE Digital",
    "Contact this week",
    "blended",
    { employabilityImpact: 9, timeFit: 5, costFit: 4, fundingAvailability: 7, strengthsAlignment: 9, stressFit: 5, longTermValue: 10 },
    ["digital literacy trainer", "TAFE/RTO trainer", "workplace trainer", "school tech trainer"],
    ["What days and workload?", "Can assessment fit around Monday/Wednesday work?"],
    "High long-term value — confirm Smart and Skilled subsidy at TAFE 131 601.",
    { cost: "Often subsidised under Smart and Skilled; full fee varies — get quote", duration: "Typically 6–12 months part-time (confirm intake)" },
  ),
  course(
    "comptia-a",
    "josh",
    "CompTIA A+",
    "CompTIA authorised training partner / online",
    "Maybe later",
    "online",
    { employabilityImpact: 7, costFit: 5, stressFit: 6 },
    ["service desk", "desktop support", "school ICT support", "MSP technician"],
    ["Is A+ valued by Dubbo employers compared with Microsoft certs?", "Can exam fees be funded?"],
    "Useful baseline; Microsoft path may be faster given current role.",
    { cost: "Training + two exams often AUD $1,500–2,500 total (shop around)", duration: "3–6 months part-time typical" },
  ),
  course(
    "cert-business",
    "josh",
    "Certificate IV in Business",
    "TAFE NSW Dubbo",
    "Maybe later",
    "blended",
    { fundingAvailability: 7 },
    ["admin officer", "customer service", "systems admin support", "library/admin support"],
    ["Can units be done online?", "Is it subsidised in NSW?"],
    "Complements La Trobe admin roles and Cert III Library — useful for council/library/school admin pathways.",
    { cost: "Smart and Skilled may apply; confirm fee before enrolment", duration: "6–18 months depending on load" },
  ),
  course(
    "first-aid",
    "both",
    "Provide First Aid (HLTAID011) + CPR",
    "Local RTO (e.g. St John / Red Cross Dubbo area)",
    "Contact this week",
    "in person",
    { timeFit: 9, stressFit: 8, costFit: 7 },
    ["school support", "community work", "nursing readiness", "training roles"],
    ["Which dates avoid Monday/Wednesday?", "Can BLS be recognised for nursing requirements?"],
    "Small practical credential that may remove application blockers.",
    { cost: "Typically AUD $120–180 for First Aid + CPR (confirm provider)", duration: "1–2 day course" },
  ),
  course(
    "immunisation",
    "kristy",
    "Immunisation nursing program",
    "APNA / accredited immunisation education provider",
    "Contact today",
    "online",
    { employabilityImpact: 10, strengthsAlignment: 9, longTermValue: 9 },
    ["GP practice nurse", "immunisation clinic", "community health", "school vaccination programs"],
    ["Is this course accepted in NSW?", "What practical components are required?", "Can funding cover fees?"],
    "Strong non-aged-care pathway — confirm NSW recognition with provider.",
    { cost: "Often AUD $500–800+ depending on provider (Parent Pathways may fund)", duration: "Several weeks including practical" },
  ),
  course(
    "gp-practice",
    "kristy",
    "GP practice nurse / chronic disease CPD bundle",
    "APNA / RACGP-approved CPD providers",
    "Contact today",
    "online",
    { employabilityImpact: 9, timeFit: 8, costFit: 7, stressFit: 8 },
    ["GP practice nurse", "clinic nurse", "chronic disease nurse", "care plan support"],
    ["Which modules matter most for GP practices?", "Do local clinics value this CPD?"],
    "Modular CPD — start with care plans and chronic disease modules relevant to Dubbo clinics.",
    { cost: "APNA membership + modules; many AUD $50–200 per module", duration: "Flexible online modules" },
  ),
  course(
    "child-family",
    "kristy",
    "Child and family health nursing pathway",
    "University postgraduate pathway (e.g. UTS/GCU)",
    "Contact this week",
    "blended",
    { employabilityImpact: 9, timeFit: 5, costFit: 3, stressFit: 6, longTermValue: 10, strengthsAlignment: 10 },
    ["child and family health nurse", "maternal/child services", "community health"],
    ["What is the minimum pathway for Dubbo roles?", "Can this wait until employment is stable?"],
    "Strong alignment with 10+ years paediatric nursing — consider after securing first Dubbo RN role.",
    { cost: "Postgraduate fees apply — HECS-HELP may be available", duration: "1–2+ years" },
  ),
  course(
    "wound-care",
    "kristy",
    "Wound management CPD",
    "Wounds Australia / recognised CPD provider",
    "Contact this week",
    "online",
    { employabilityImpact: 7, timeFit: 8, costFit: 7 },
    ["GP practice nurse", "clinic nurse", "outpatient nurse", "community health nurse"],
    ["Is the provider recognised?", "Will this help with clinic applications?"],
    "Practical CPD supporting clinic and GP applications.",
    { cost: "Often AUD $150–400 depending on module bundle", duration: "Self-paced online" },
  ),
];

export const contactsSeed: Contact[] = [
  {
    id: "contact-spinifex",
    agencyId: "spinifex",
    personContacted: "",
    channel: "Phone",
    lastContact: "",
    nextFollowUp: "",
    notes: "Call 02 6884 1298 — Thursday/Friday ICT, admin, customer service, school support.",
    status: "Not started",
  },
  {
    id: "contact-yilabara",
    agencyId: "yilabara",
    personContacted: "",
    channel: "Email",
    lastContact: "",
    nextFollowUp: "",
    notes: "Email parents-dubbo@yilabara.org.au — eligibility, CPD funding, checks, next appointment.",
    status: "Not started",
  },
];

const emptyChecklist = () =>
  Object.fromEntries(DEFAULT_CHECKLIST_ITEMS.map((item) => [item, false])) as Record<string, boolean>;

export const parentPathwaysSeed: ParentPathwaysState = {
  eligibility:
    "Parent Pathways (Western NSW): free voluntary support for eligible parents/carers of children under 6. Confirm Kristy's eligibility even if not on Parenting Payment.",
  providerContact: "Yilabara Dubbo — Suite 2, First Floor, 64 Talbragar St | 02 5858 4597 | parents-dubbo@yilabara.org.au",
  appointmentNotes: "",
  goalsDiscussed:
    "Relocated to Dubbo. Kristy: paediatric RN (Bendigo Health Children's Ward to Jan 2026) seeking family-friendly non-aged-care work. Josh: Avance MSP ICT Mon/Wed, seeking Thu/Fri bridge work.",
  trainingRecommended: "Immunisation, GP practice nurse CPD, CPR/BLS update, child/family health pathway when ready.",
  fundingAvailable:
    "May cover course fees, WWCC, police check, transport, laptop/phone, and work-related costs — confirm individual fund caps at appointment.",
  individualFundUsage: "",
  documentsNeeded: ["ID", "AHPRA registration", "resume", "course quotes", "WWCC/police check info if required"],
  nextAppointment: "",
  agreedNextSteps: "Book first appointment via parents-dubbo@yilabara.org.au; bring checklist and course quotes.",
  yilabaraChecklistItems: [...DEFAULT_CHECKLIST_ITEMS],
  yilabaraChecklist: emptyChecklist(),
};
