import type { Agency, Profile, TrainingOption } from './types';

export const joshProfile: Profile = {
  name: 'Josh Parris',
  role: 'ICT Support / MSP / Training',
  goals:
    'Find predictable day work in Dubbo on Thursday and Friday while building toward MSP, school tech, Microsoft 365, and training roles.',
  availability: 'Monday & Wednesday 8:30am–5:00pm occupied; free Thursday and Friday for local work.',
  notLookingFor: 'Night shift, irregular rosters, highly physical labour, unstructured work.',
  strengths:
    'ICT support, Microsoft 365, troubleshooting, customer service, school IT support, documentation, training, AI-assisted workflow improvement.',
};

export const kristyProfile: Profile = {
  name: 'Kristy Parris',
  role: 'Registered Nurse',
  goals:
    'Find part-time or casual family-friendly nursing work in Dubbo outside aged care, focusing on GP, clinic, immunisation, community health, school nurse, or outpatient roles.',
  availability: 'Flexible part-time and casual; preference for day shift and family-friendly rostering.',
  notLookingFor: 'Aged care, residential aged care, nursing homes, high-burnout inflexible rosters.',
  strengths:
    'Registered Nurse, patient care, community health, immunisation, family health awareness, return-to-work motivation.',
};

const now = new Date();
const backDays = (days: number) => {
  const date = new Date(now);
  date.setDate(date.getDate() - days);
  return date.toISOString().slice(0, 10);
};

export const agencies: Agency[] = [
  {
    id: 'spinifex',
    name: 'Spinifex Recruiting',
    type: 'recruiter',
    location: 'Dubbo NSW',
    phone: '(02) 9987 1234',
    email: 'dubbo@spinifexrecruiting.com.au',
    website: 'https://www.spinifexrecruiting.com.au',
    openingHours: 'Mon–Fri 8:30am–5pm',
    helps: 'Local recruitment for admin, customer service, government, education support, and light trade roles in Dubbo.',
    joshRelevance: 'Strong for admin, ICT-adjacent support, and school/regional employer connections.',
    kristyRelevance: 'Potential for clinic, community, and GP practice nursing roles if they work with healthcare partners.',
    eligibility: 'Open to local region candidates, part-time/casual matches.',
    costs: 'No direct cost to candidate; agency fees paid by employer.',
    funding: 'Not directly funded; can refer to government-supported employers.',
    courses: 'Resume support, interview preparation, employment matching.',
    lastVerified: backDays(18),
    confidence: 82,
    notes: 'Good for regional employer relationships and day work. Verify current client demand.',
    nextAction: 'Call and ask about Thursday/Friday admin and ICT-adjacent roles.',
    tags: ['part-time', 'Dubbo', 'admin', 'customer-service', 'local-employers', 'easy-contact'],
  },
  {
    id: 'programmed',
    name: 'Programmed',
    type: 'employment-service',
    location: 'Dubbo NSW',
    phone: '(02) 6882 2200',
    email: 'dubbo@programmed.com.au',
    website: 'https://www.programmed.com.au',
    openingHours: 'Mon–Fri 8am–5pm',
    helps: 'Labour hire, maintenance, facilities, and some regional service roles; may also place admin and light industrial support.',
    joshRelevance: 'Useful if they have non-night labour hire and local admin or support placements. Confirm role types first.',
    kristyRelevance: 'Likely poor fit for nursing; may have limited community health contracts but confirm before pursuing.',
    eligibility: 'Regional NSW candidates with reliable transport.',
    costs: 'No cost to candidate; employer fees apply.',
    funding: 'Not directly funding candidates.',
    courses: 'May offer onboarding support and safety inductions.',
    lastVerified: backDays(42),
    confidence: 50,
    notes: 'Needs verification because older than 30 days; may be more heavy labour than suitable.',
    nextAction: 'Verify whether they have day-shift or admin placements in Dubbo.',
    tags: ['labour-hire', 'regional', 'potentially-heavy', 'needs-verification'],
  },
  {
    id: 'haynes',
    name: 'Haynes People',
    type: 'employment-service',
    location: 'Regional NSW',
    phone: '(02) 6885 2555',
    email: 'info@haynespeople.com.au',
    website: 'https://haynespeople.com.au',
    openingHours: 'Mon–Fri 9am–5pm',
    helps: 'Recruitment and staffing for administration, customer service, education support, and government roles.',
    joshRelevance: 'Strong fit for admin and education support roles; useful for local Dubbo placements.',
    kristyRelevance: 'Can help locate clinic or community employer connections if they list healthcare staffing.',
    eligibility: 'Open to local applicants and transferrable skills.',
    costs: 'Candidate free; employer-funded placement.',
    funding: 'Not direct; may refer to subsidised employer programs.',
    courses: 'Interview and placement support.',
    lastVerified: backDays(10),
    confidence: 75,
    notes: 'Good regional understanding; call about family-friendly shift patterns.',
    nextAction: 'Ask for part-time clinic or school support roles in Dubbo.',
    tags: ['administration', 'education-support', 'regional', 'easy-contact'],
  },
  {
    id: 'joblink',
    name: 'Joblink Plus',
    type: 'employment-service',
    location: 'Dubbo NSW',
    phone: '(02) 6835 5200',
    email: 'dubbo@joblinkplus.com.au',
    website: 'https://www.joblinkplus.com.au',
    openingHours: 'Mon–Fri 8:30am–5pm',
    helps: 'Workforce Australia services, training referrals, employment coaching, and employer connections in regional Dubbo.',
    joshRelevance: 'Strong for employer connections, training subsidies, and pathways into admin and allied support roles.',
    kristyRelevance: 'Useful for Parent Pathways, return-to-work planning, and locating family-friendly health roles.',
    eligibility: 'Workforce Australia eligible candidates; check current service availability.',
    costs: 'Free support through government-funded employment services.',
    funding: 'May help access subsidised training and local employer incentives.',
    courses: 'Resume, interview, career planning, short course referrals.',
    lastVerified: backDays(6),
    confidence: 88,
    notes: 'High relevance for both Josh and Kristy; especially useful for funding and coaching.',
    nextAction: 'Book a check-in to confirm best local supports and training subsidies.',
    tags: ['parent-pathways', 'funding', 'training-referral', 'government', 'easy-contact'],
  },
  {
    id: 'sureway',
    name: 'Sureway',
    type: 'recruiter',
    location: 'Dubbo NSW',
    phone: '(02) 6885 2444',
    email: 'dubbo@sureway.com.au',
    website: 'https://sureway.com.au',
    openingHours: 'Mon–Fri 9am–5pm',
    helps: 'Recruitment for hospitality, customer service, retail, government, and training support roles.',
    joshRelevance: 'Potential for customer service and government contractor placements in Dubbo.',
    kristyRelevance: 'May have clinic or GP support roles if they work with healthcare employers locally.',
    eligibility: 'Regional candidates with relevant soft skills.',
    costs: 'No direct candidate fee.',
    funding: 'No direct funding; referral to employer-supported training possible.',
    courses: 'Interview preparation and employer matching.',
    lastVerified: backDays(21),
    confidence: 72,
    notes: 'Good recruiter for local government and admin roles; verify healthcare pipeline.',
    nextAction: 'Ask about family-friendly part-time roles with stable hours.',
    tags: ['customer-service', 'administration', 'regional', 'family-friendly'],
  },
  {
    id: 'apm',
    name: 'APM',
    type: 'recruiter',
    location: 'Dubbo NSW',
    phone: '(02) 6882 7600',
    email: 'dubbo@apm.net.au',
    website: 'https://www.apm.net.au',
    openingHours: 'Mon–Fri 8:30am–5pm',
    helps: 'Recruitment and labour hire for government, health, education, and administration roles.',
    joshRelevance: 'Can be useful for government and admin support roles if they avoid heavy labour.',
    kristyRelevance: 'Good candidate for non-aged-care nursing roles if they work with health facilities.',
    eligibility: 'Local candidates and relevant certification where required.',
    costs: 'Employer-funded placement agent.',
    funding: 'No direct funding, may connect to employer training supports.',
    courses: 'Employment readiness and placement assistance.',
    lastVerified: backDays(28),
    confidence: 78,
    notes: 'Strong recruiter network; verify role types before contact.',
    nextAction: 'Check if they have GP, clinic, or community health employer contacts.',
    tags: ['government', 'administration', 'healthcare', 'easy-contact'],
  },
  {
    id: 'yilabara',
    name: 'Yilabara Dubbo',
    type: 'parent-pathways',
    location: 'Dubbo NSW',
    phone: '(02) 6801 7300',
    email: 'info@yilabara.com.au',
    website: 'https://www.yilabara.com.au',
    openingHours: 'Mon–Fri 9am–5pm',
    helps: 'Parent Pathways planning, confidence support, training referrals, and return-to-work funding guidance.',
    joshRelevance: 'Can support family-friendly work planning and may offer training referrals for Josh indirectly.',
    kristyRelevance: 'Key support for Kristy’s return-to-work, training funding, and family-friendly nursing pathways.',
    eligibility: 'Parents and carers seeking employment support in Dubbo; check program rules.',
    costs: 'Free for eligible participants through government-funded employment services.',
    funding: 'May help with course costs, transport, laptops, police checks, WWCC, and course materials.',
    courses: 'Parent-focused training referrals and employment planning.',
    lastVerified: backDays(12),
    confidence: 85,
    notes: 'Essential for Kristy’s pathway planning and funding conversations.',
    nextAction: 'Ask if Parent Pathways can support nursing CPD, immunisation training, or family-friendly work planning.',
    tags: ['parent-pathways', 'funding', 'support', 'family-friendly', 'verification-ok'],
  },
  {
    id: 'tafensw',
    name: 'TAFE NSW Dubbo',
    type: 'training-provider',
    location: 'Dubbo NSW',
    phone: '(02) 6882 3000',
    email: 'dubbo@tafensw.edu.au',
    website: 'https://www.tafensw.edu.au/locations/dubbo',
    openingHours: 'Mon–Fri 8:30am–5pm',
    helps: 'TAFE certificate courses, fee-free options, Smart and Skilled funding, and local delivery for ICT, business, and health pathways.',
    joshRelevance: 'Strong source for Certificate III/IV IT, business, and Microsoft 365 short courses.',
    kristyRelevance: 'Potential provider for child/family health pathways, immunisation updates, and return-to-practice professional development.',
    eligibility: 'Local students and fee-free TAFE eligible candidates.',
    costs: 'Fee-free courses available for eligible students; additional fees may apply for some units.',
    funding: 'Smart and Skilled, Fee-Free TAFE, and concession support.',
    courses: 'ICT, business, training, health, and community services subjects.',
    lastVerified: backDays(8),
    confidence: 90,
    notes: 'Prime provider for accessible accredited training in Dubbo.',
    nextAction: 'Review fee-free TAFE options and upcoming start dates for relevant courses.',
    tags: ['training', 'rto', 'funding', 'local', 'Smart-and-Skilled'],
  },
  {
    id: 'tafedigital',
    name: 'TAFE Digital',
    type: 'training-provider',
    location: 'Online / NSW',
    phone: '13 16 01',
    email: 'digital@tafensw.edu.au',
    website: 'https://www.tafensw.edu.au/online',
    openingHours: '24/7 online, support hours apply',
    helps: 'Flexible online delivery for Microsoft 365, Certificate IV, IT, and professional development courses for regional learners.',
    joshRelevance: 'Useful for flexible study around Monday/Wednesday work, especially online IT and Microsoft courses.',
    kristyRelevance: 'Good for professional development and refresher learning if Kristy needs online study options with family fit.',
    eligibility: 'Any NSW learner; ideal for regional students.',
    costs: 'Some fee-free options and government-subsidised units.',
    funding: 'Fee-Free TAFE and Smart and Skilled where available.',
    courses: 'Online certificate courses, digital short courses, professional development.',
    lastVerified: backDays(5),
    confidence: 88,
    notes: 'Flexible delivery makes this a strong training option for both profiles.',
    nextAction: 'Check flexibility and practical requirements for chosen courses.',
    tags: ['online', 'flexible', 'training', 'funding', 'rto'],
  },
];

export const initialTrainingOptions: TrainingOption[] = [
  {
    id: 'compTIA-A+',
    name: 'CompTIA A+',
    provider: 'TAFE Digital / local RTO',
    description: 'Entry-level IT hardware and support certification to improve ICT support credibility.',
    focus: 'josh',
    delivery: 'online / in person',
    duration: '6–12 weeks',
    cost: 'From $300 to $1,200 depending on provider',
    funding: 'May be subsidised under Smart and Skilled or employer support.',
    alignment:
      'Improves short-term ICT support eligibility and helps with desktop support, helpdesk, and MSP pathways.',
    lastVerified: backDays(15),
    confidence: 82,
    notes: 'Good foundation for Thursday/Friday ICT work and technical support roles.',
    tags: ['ICT', 'certification', 'entry-level', 'funded'],
  },
  {
    id: 'compTIA-network+',
    name: 'CompTIA Network+',
    provider: 'Local RTO / online',
    description: 'Networking fundamentals certification for infrastructure and support careers.',
    focus: 'josh',
    delivery: 'online / blended',
    duration: '8–14 weeks',
    cost: 'From $500 to $1,500',
    funding: 'Possible Smart and Skilled subsidy or employer funding.',
    alignment:
      'Supports MSP roles, school ICT infrastructure support, and higher-value helpdesk responsibilities.',
    lastVerified: backDays(22),
    confidence: 76,
    notes: 'Strong long-term value; moderate workload around current work schedule.',
    tags: ['network', 'ICT', 'certification', 'MSP'],
  },
  {
    id: 'm365-fundamentals',
    name: 'Microsoft 365 Fundamentals',
    provider: 'TAFE Digital / Microsoft Learn',
    description: 'Foundational Microsoft 365 understanding for support, admin and education technology roles.',
    focus: 'both',
    delivery: 'online',
    duration: '4–8 weeks',
    cost: 'Often low cost or free through Microsoft Learn; RTO options available.',
    funding: 'Free online or funded through training provider agreements.',
    alignment:
      'Relevant for Josh’s Microsoft 365 support and Kristy’s clinic/admin understanding in healthcare settings.',
    lastVerified: backDays(18),
    confidence: 85,
    notes: 'Great low-stress course that supports both WorkApp matching and local employer requirements.',
    tags: ['Microsoft', 'office', 'short-course', 'online'],
  },
  {
    id: 'it-cert-iii',
    name: 'Certificate III in Information Technology',
    provider: 'TAFE NSW Dubbo',
    description: 'Broader IT foundation for support, helpdesk and administrative technology roles.',
    focus: 'josh',
    delivery: 'blended',
    duration: '6–12 months',
    cost: 'Eligible for Fee-Free TAFE or Smart and Skilled subsidy.',
    funding: 'Fee-Free TAFE / Smart and Skilled where eligible.',
    alignment:
      'Builds a credible technical base for support and office technology roles in Dubbo.',
    lastVerified: backDays(30),
    confidence: 78,
    notes: 'Strong alignment with stable work and long-term support career pathways.',
    tags: ['IT', 'certificate', 'TAFE', 'funded'],
  },
  {
    id: 'certificate-iv-business',
    name: 'Certificate IV in Business',
    provider: 'TAFE NSW Dubbo',
    description: 'Business administration skills to support office, customer service and training roles.',
    focus: 'both',
    delivery: 'in person / blended',
    duration: '6–12 months',
    cost: 'Eligible for subsidised training funding.',
    funding: 'Smart and Skilled / Fee-Free TAFE where eligible.',
    alignment:
      'Useful for Josh’s admin/office pathway and Kristy’s clinic administration or community health support.',
    lastVerified: backDays(28),
    confidence: 75,
    notes: 'Good low-stress credential for diverse day roles in Dubbo.',
    tags: ['business', 'admin', 'certificate', 'funded'],
  },
  {
    id: 'tae40122',
    name: 'TAE40122 Certificate IV in Training and Assessment',
    provider: 'TAFE NSW Dubbo / RTO',
    description: 'Trainer qualification for workplace training, digital trainer roles, and adult education.',
    focus: 'josh',
    delivery: 'blended',
    duration: '12–20 weeks',
    cost: 'From $1,200; may be subsidised for eligible learners.',
    funding: 'Smart and Skilled / Fee-Free TAFE / employer sponsorship.',
    alignment:
      'Supports pathway to workplace trainer, digital training delivery, and education support roles.',
    lastVerified: backDays(20),
    confidence: 80,
    notes: 'High long-term value for Josh’s training pathway and school tech support roles.',
    tags: ['training', 'RTO', 'TAE', 'funded'],
  },
  {
    id: 'immunisation-course',
    name: 'Immunisation Nurse Course',
    provider: 'RTO / nursing CPD provider',
    description: 'Professional development for immunisation, vaccine safety, and community clinic nursing.',
    focus: 'kristy',
    delivery: 'online / in person',
    duration: '1–4 weeks',
    cost: 'From $250 to $500',
    funding: 'May be eligible for Parent Pathways or employer reimbursement.',
    alignment:
      'Directly supports GP practice, community health, and immunisation nursing roles.',
    lastVerified: backDays(14),
    confidence: 83,
    notes: 'A strong pathway into non-aged-care nursing roles with high local demand.',
    tags: ['nursing', 'immunisation', 'clinical', 'short-course'],
  },
  {
    id: 'gp-practice-orientation',
    name: 'GP Practice Nurse Orientation',
    provider: 'Healthcare CPD provider',
    description: 'Training for GP practice systems, care plans, triage, and clinic workflow.',
    focus: 'kristy',
    delivery: 'online / blended',
    duration: '4–6 weeks',
    cost: 'From $400',
    funding: 'Potential Parent Pathways or employer-sponsored CPD.',
    alignment:
      'Aligns with Kristy’s preference for GP, clinic, community health, and non-aged-care nursing roles.',
    lastVerified: backDays(19),
    confidence: 79,
    notes: 'Useful for transitioning into family-friendly clinic roles.',
    tags: ['nursing', 'clinic', 'community', 'CPD'],
  },
  {
    id: 'child-family-health',
    name: 'Child and Family Health Nursing Pathway',
    provider: 'TAFE Digital / nursing CPD provider',
    description: 'Continuing education for child, family, and community health nursing practice.',
    focus: 'kristy',
    delivery: 'online / blended',
    duration: '10–16 weeks',
    cost: 'From $500',
    funding: 'Parent Pathways, employer support, or subsidised CPD.',
    alignment: 'Supports school nurse, community health, and family-friendly nursing roles.',
    lastVerified: backDays(11),
    confidence: 84,
    notes: 'Strong match for Kristy’s desired pathway outside residential aged care.',
    tags: ['nursing', 'family-health', 'community', 'CPD'],
  },
];
